### ISSUE TITLE
Missing Usage guidelines

### ISSUE THREAD

**Issue by Noxdor** [OpenModelica/OpenModelicaDockerImages#2]
Please put information on how to use these images!

I am new to Modelica and it is honestly very disencouraging how complicated it is to install! I am an Arch derivative, so there is no package for my system that is easy to install. Neither is there an AppImage or a package on Flathub.

The docker image is the most modern and potentially easy way I could find to use Modelica on my platform. But there is no guidance on how to run the container to get it working. Instead there is the link to this github repo, which only links back to the docker hub page, which isn't very helpful!

Please improve on ways to install and use Modelica. The entry barrier right now feels way to high, at least for me as a Linux developer that doesn't run a Debian variant or RedHat Software.

**Comment by adrpo** [comment]
Yes, we would need to add some HOWTOs, but we're rather busy with other stuff, mostly adding functionality to OpenModelica (OM) and fixing bugs. Have you tried to compile OM yourself from sources?

I will ask one of our docker experts if he can spare some time to write a small introduction.
